Introduce lock to prevent race condition
Traceback (most recent call last):
  File "C:\Users\woos8\Documents\GitHub\DGU2020_COVID_back\webapi\views.py", line 510, in post
    result = mut_func.get_mutation(temp_file_names[0], temp_file_names[1])
  File "C:\Users\woos8\Documents\GitHub\DGU2020_COVID_back\extern\DGU2020_covid_database\src\dgucovidb\mutation_interface.py", line 187, in get_mutation
    shutil.rmtree(f'{self.work_dir}/temp')
  File "C:\Program Files\Python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python38\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Python38\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '.\\./tmp/temp\\fasta_for_align.fasta'